#! /usr/bin/env bash

# Generate 3 random lowercase words (6 letters each)
word1=$(tr -dc 'a-z' </dev/urandom | head -c6)
word2=$(tr -dc 'a-z' </dev/urandom | head -c6)
word3=$(tr -dc 'a-z' </dev/urandom | head -c6)
word4=$(tr -dc 'a-z' </dev/urandom | head -c6)

# Export variables for use in find -exec
export word1 word2 word3 word4

# Rename directories
find . -depth -type d -name 'com' -execdir mv {} "$word1" \;
find . -depth -type d -name 'vortex' -execdir mv {} "$word2" \;
find . -depth -type d -name 'vortex' -execdir mv {} "$word3" \;
find . -depth -type d -name 'io' -execdir mv {} "$word4" \;

# Replace inside files
find . -type f -exec sed -i \
    -e "s/com\.vortex\.vortex/$word1.$word2.$word3/g" \
    -e "s/io\.vortex\.vortex/$word4.$word2.$word3/g" \
    -e "s/com\.vortex\.zako/$word1.$word2.zako/g" \
    -e "s/com\/vortex\/vortex/$word1\/$word2\/$word3/g" \
    -e "s/io\/vortex\/vortex/$word4\/$word2\/$word3/g" \
    -e "s/io_vortex_vortex/${word4}_${word2}_${word3}/g" \
    -e "s/com_vortex_vortex/${word1}_${word2}_${word3}/g" {} +

# add -spoofed on version
sed -i 's/v3\.2\.0"/v3.2.0-spoofed"/g' build.gradle.kts
